# Making changes? https://github.com/nektos/act may help you test locally

name: Build with GitHub Actions

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Check out
        uses: actions/checkout@v4
      - name: "Setup JDK 8"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Give permission
        run: chmod +x ./gradlew

      # Actually build
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Uploaded
          path: |
            build/libs/*.jar
