# Making changes? https://github.com/nektos/act may help you test locally

name: Build with GitHub Actions

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:
  release:
    types: [released]

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

env:
  RUNTIME_VERSION: 21

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"

    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      # Setup
      - name: Check out
        uses: actions/checkout@v4
      - name: "Setup JDK ${{ env.RUNTIME_VERSION }}"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "${{ env.RUNTIME_VERSION }}"
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      # Actually build
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive test results
        if: "${{ always() }}"
        uses: actions/upload-artifact@v4
        with:
          name: "${{ runner.os }}-test-results"
          path: |
            build/reports/
